spring.application.name=cinema
# Servidor
server.port=8082
server.servlet.context-path=/app-cinema

# H2 Database
spring.datasource.url=jdbc:h2:mem:appschooldb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# H2 Console (acess\u00c3\u00advel em /app-cinema/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Logs
logging.level.com.example.appcinema=DEBUG
